version: '2' 

services:
  db:
    image: "postgres:11.2-alpine"
    command: -c 'log_min_duration_statement=100'
    restart: unless-stopped
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./data/db-startup:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: game
      POSTGRES_USER: game
      POSTGRES_PASSWORD: game_pass
  redis:
    image: redis:6-alpine
  server:
    build: server
    image: registry.phd.madg.es/lingtowns-server:0.0.9
    restart: unless-stopped
    volumes:
      - ./server/:/app
     #- /Users/chrismadge/PhD/PhraseDetectivesCorpora/:/data
    environment:
      #- EXT_URL:https://lingotowns.com
      #- EXT_URL=http://localhost:8081
      - EXT_URL=https://lingotowns.com
      - REDIS_HOST=redis
      - FLASK_DEBUG=True
      - FLASK_ENV=development
    depends_on:
      - redis
      - db
  http:
    image: nginx
    volumes:
      - ./server/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./server/static:/app/
    ports:
      - 8025:80
    depends_on:
      - server
