version: '2' 

services:
  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379
  server:
    build: server
    image: registry.phd.madg.es/lingtowns-server:0.0.8
    restart: unless-stopped
    ports:
      - 8081:5000
    volumes:
      - ./server/:/app
     #- /Users/chrismadge/PhD/PhraseDetectivesCorpora/:/data
    environment:
      #- EXT_URL:https://lingotowns.com
      - EXT_URL=http://localhost:8081
      - REDIS_HOST=redis
      - FLASK_DEBUG=True
      - FLASK_ENV=development
    depends_on:
      - redis
  http:
    image: nginx
    volumes:
      - ./server/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./server/static:/app/
    ports:
      - 8080:80
    depends_on:
      - server
