version: '2' 

services:
  server:
    build: server
    image: registry.phd.madg.es/lingtowns-server:0.0.3
    restart: unless-stopped
    ports:
      - 8081:5000
    volumes:
      - ./server/:/app
      - /Users/chrismadge/PhD/PhraseDetectivesCorpora/:/data
    environment:
      - FLASK_DEBUG:True
      - FLASK_ENV:development
  http:
    image: nginx
    volumes:
      - ./server/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/app/
    ports:
      - 8080:80
    depends_on:
      - server
